### ISSUE TITLE
Error in importing to BUrpsuite

### ISSUE THREAD

**Issue by bevennyamande** [BitTheByte/BitMapper#3]
- The application is showing errors in Burpsuite.
-  Probably the AI messed stuff

**Comment by CarlesLlobet** [comment]
Should be closed with PR #4. Could you confirm @bevennyamande?

**Comment by bevennyamande** [comment]
ok i this its sorted now

**Comment by BitTheByte** [comment]
Thanks @bevennyamande for the confirmation
